name = "art-name-wip"
type = "javascript"
workers_dev = true
# Add your account ID here
account_id = ""

[build.upload]
format = "modules"
dir = "worker"
main = "./art.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ArtRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]